create table employees (
	id BIGSERIAL PRIMARY KEY,
	first_name VARCHAR(50) NOT NULL,
	last_name VARCHAR(50) NOT NULL,
	email VARCHAR(50),
	gender VARCHAR(50) NOT NULL,
	date_of_birth DATE NOT NULL,
	country_of_birth VARCHAR(50)
);
insert into employees (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Mable', 'Whines', 'mwhines0@aboutads.info', 'Female', '2020-05-11', 'Indonesia');
insert into employees (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Winn', 'Steagall', 'wsteagall1@cnbc.com', 'Male', '2020-06-18', 'Colombia');
insert into employees (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Dillon', 'Cockhill', null, 'Male', '2020-07-03', 'Sierra Leone');
insert into employees (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Berry', 'Kinnaird', 'bkinnaird3@oracle.com', 'Female', '2020-01-12', 'Nepal');
insert into employees (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Cheri', 'Hamlin', 'chamlin4@guardian.co.uk', 'Female', '2020-07-22', 'Czech Republic');
insert into employees (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Lyssa', 'Mahaffey', null, 'Female', '2019-12-17', 'Ivory Coast');
insert into employees (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Marina', 'Siveter', 'msiveter6@cmu.edu', 'Female', '2020-01-23', 'Argentina');
insert into employees (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Sibby', 'Mallinar', 'smallinar7@ucsd.edu', 'Female', '2019-09-13', 'Russia');
insert into employees (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Mariya', 'Rainton', 'mrainton8@state.gov', 'Female', '2020-07-27', 'China');
insert into employees (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Fallon', 'Dumberrill', null, 'Female', '2020-06-01', 'China');
insert into employees (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Pandora', 'Gallahar', null, 'Female', '2020-08-13', 'Sweden');
insert into employees (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Aldus', 'Sarch', 'asarchb@hubpages.com', 'Male', '2020-05-15', 'Mexico');
insert into employees (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Nanette', 'Kiloh', 'nkilohc@ibm.com', 'Female', '2020-05-02', 'Philippines');
insert into employees (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Moises', 'Keuntje', 'mkeuntjed@netlog.com', 'Male', '2019-10-05', 'Brazil');
insert into employees (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Hattie', 'Rodwell', null, 'Female', '2020-01-02', 'China');
insert into employees (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Turner', 'Brandreth', 'tbrandrethf@usnews.com', 'Male', '2020-04-27', 'Mongolia');
insert into employees (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Aeriel', 'Rotge', 'arotgeg@vk.com', 'Female', '2020-05-12', 'Canada');
insert into employees (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Jesse', 'Menlow', 'jmenlowh@lulu.com', 'Female', '2019-09-01', 'Russia');
insert into employees (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Wash', 'Fennelly', null, 'Male', '2020-03-29', 'Portugal');
insert into employees (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Lonee', 'Cacacie', 'lcacaciej@dion.ne.jp', 'Female', '2019-11-26', 'Brazil');
insert into employees (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Flora', 'Barter', 'fbarterk@youtube.com', 'Female', '2020-02-10', 'China');
insert into employees (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Robbert', 'Scranny', 'rscrannyl@archive.org', 'Male', '2020-06-30', 'Russia');
insert into employees (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Lisette', 'Jackett', null, 'Female', '2019-12-19', 'China');
insert into employees (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Othella', 'Swanger', 'oswangern@ning.com', 'Female', '2020-03-12', 'South Korea');
insert into employees (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Che', 'Whales', null, 'Male', '2019-12-11', 'Japan');
insert into employees (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Wat', 'Helks', null, 'Male', '2020-06-11', 'China');
insert into employees (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Rinaldo', 'Jowitt', 'rjowittq@huffingtonpost.com', 'Male', '2020-07-12', 'Portugal');
insert into employees (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Rube', 'Daudray', 'rdaudrayr@ehow.com', 'Male', '2019-12-30', 'Poland');
insert into employees (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Daisy', 'Gabbetis', null, 'Female', '2020-02-01', 'Portugal');
insert into employees (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Murray', 'Slader', 'msladert@1und1.de', 'Male', '2019-09-20', 'China');
insert into employees (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Trevar', 'Fitt', 'tfittu@ebay.co.uk', 'Male', '2020-01-21', 'Mexico');
insert into employees (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Isadora', 'Edinburough', 'iedinburoughv@cnet.com', 'Female', '2020-06-10', 'Russia');
insert into employees (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Angelita', 'Drugan', null, 'Female', '2020-08-08', 'Iran');
insert into employees (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Teador', 'Yeaman', 'tyeamanx@salon.com', 'Male', '2019-08-23', 'Portugal');
insert into employees (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Drucill', 'Gledhill', null, 'Female', '2020-08-19', 'France');
insert into employees (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Renee', 'Cocke', null, 'Female', '2019-08-30', 'Nepal');
insert into employees (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Valry', 'Boykett', 'vboykett10@mail.ru', 'Female', '2020-04-12', 'Poland');
insert into employees (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Crichton', 'Marples', 'cmarples11@china.com.cn', 'Male', '2020-05-29', 'United States');
insert into employees (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Lyon', 'McCorry', 'lmccorry12@un.org', 'Male', '2020-04-10', 'Indonesia');
insert into employees (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Thane', 'Sowerbutts', null, 'Male', '2020-01-25', 'Russia');
insert into employees (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Franchot', 'Hallsworth', 'fhallsworth14@theglobeandmail.com', 'Male', '2020-06-27', 'Ghana');
insert into employees (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Steffi', 'Solon', null, 'Female', '2020-01-18', 'Ukraine');
insert into employees (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Lanny', 'De Andisie', 'ldeandisie16@icq.com', 'Female', '2020-03-16', 'Indonesia');
insert into employees (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Staford', 'Hourigan', 'shourigan17@hp.com', 'Male', '2020-01-09', 'United States');
insert into employees (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Eolande', 'Bulfield', 'ebulfield18@elegantthemes.com', 'Female', '2019-09-11', 'Cyprus');
insert into employees (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Gustavo', 'Wilkison', null, 'Male', '2019-12-29', 'Peru');
insert into employees (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Osmond', 'Sperry', 'osperry1a@godaddy.com', 'Male', '2020-03-21', 'Brazil');
insert into employees (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Jesse', 'Andersson', 'jandersson1b@mozilla.com', 'Male', '2020-06-23', 'Indonesia');
insert into employees (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Gabriele', 'Riggeard', 'griggeard1c@drupal.org', 'Male', '2020-03-22', 'Serbia');
insert into employees (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Ludvig', 'Beckworth', 'lbeckworth1d@live.com', 'Male', '2019-08-24', 'China');
insert into employees (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Clayborn', 'Reddan', 'creddan1e@un.org', 'Male', '2019-09-23', 'Portugal');
insert into employees (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Shalna', 'Menure', null, 'Female', '2020-02-11', 'Greece');
insert into employees (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Cody', 'Ladbrooke', null, 'Female', '2020-02-25', 'Russia');
insert into employees (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Deb', 'Bedow', 'dbedow1h@redcross.org', 'Female', '2020-02-26', 'Russia');
insert into employees (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Jerrold', 'Lydiard', null, 'Male', '2020-07-17', 'Russia');
insert into employees (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Onida', 'Beale', 'obeale1j@51.la', 'Female', '2020-02-14', 'United States');
insert into employees (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Burl', 'Stoney', null, 'Male', '2020-02-21', 'China');
insert into employees (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Corene', 'Annetts', 'cannetts1l@weibo.com', 'Female', '2020-02-19', 'Nigeria');
insert into employees (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Fanya', 'Feye', 'ffeye1m@squarespace.com', 'Female', '2019-12-08', 'China');
insert into employees (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Ailyn', 'Farquar', null, 'Female', '2020-04-08', 'Indonesia');
insert into employees (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Mathe', 'August', 'maugust1o@sina.com.cn', 'Male', '2020-03-16', 'Sweden');
insert into employees (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Shermie', 'Coaten', null, 'Male', '2019-10-21', 'Brazil');
insert into employees (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Walton', 'Kalisz', 'wkalisz1q@sourceforge.net', 'Male', '2019-09-21', 'China');
insert into employees (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Eydie', 'Cleaver', 'ecleaver1r@ask.com', 'Female', '2020-03-18', 'Mexico');
insert into employees (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Arnaldo', 'Bristow', 'abristow1s@gmpg.org', 'Male', '2020-01-01', 'Russia');
insert into employees (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Eugene', 'Machans', 'emachans1t@blinklist.com', 'Male', '2019-09-09', 'Finland');
insert into employees (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Husain', 'Windrus', 'hwindrus1u@github.com', 'Male', '2020-01-28', 'Sweden');
insert into employees (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Adey', 'Edgeson', null, 'Female', '2020-02-14', 'Mongolia');
insert into employees (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Sheridan', 'Torrijos', 'storrijos1w@themeforest.net', 'Male', '2019-09-06', 'Canada');
insert into employees (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Shanon', 'Rumming', 'srumming1x@bluehost.com', 'Female', '2020-01-09', 'Portugal');
insert into employees (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Giorgi', 'Byrkmyr', 'gbyrkmyr1y@weebly.com', 'Male', '2019-12-24', 'Ukraine');
insert into employees (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Sybyl', 'Jeacop', 'sjeacop1z@livejournal.com', 'Female', '2020-04-17', 'China');
insert into employees (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Tedman', 'Barg', null, 'Male', '2020-01-23', 'Brazil');
insert into employees (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Jessey', 'Vass', null, 'Male', '2020-03-18', 'Morocco');
insert into employees (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Berne', 'Mapplebeck', 'bmapplebeck22@ihg.com', 'Male', '2020-02-01', 'Indonesia');
insert into employees (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Batsheva', 'Legging', 'blegging23@woothemes.com', 'Female', '2020-04-20', 'China');
insert into employees (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Arliene', 'Durtnell', 'adurtnell24@canalblog.com', 'Female', '2020-03-26', 'China');
insert into employees (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Ricoriki', 'Stanlack', 'rstanlack25@usa.gov', 'Male', '2020-04-17', 'Armenia');
insert into employees (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Elaine', 'Gamon', 'egamon26@samsung.com', 'Female', '2020-07-03', 'Ukraine');
insert into employees (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Lanni', 'Le Quesne', null, 'Female', '2019-11-25', 'Brazil');
insert into employees (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Meir', 'Benion', null, 'Male', '2020-06-10', 'Sweden');
insert into employees (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Farand', 'Gamlen', null, 'Female', '2019-10-12', 'Brazil');
insert into employees (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Bruno', 'Drakes', 'bdrakes2a@feedburner.com', 'Male', '2020-01-07', 'Indonesia');
insert into employees (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Tony', 'Devonald', 'tdevonald2b@over-blog.com', 'Male', '2020-05-06', 'Poland');
insert into employees (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Barry', 'Pont', null, 'Male', '2020-03-12', 'Portugal');
insert into employees (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Collete', 'Castles', null, 'Female', '2020-03-11', 'Russia');
insert into employees (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Aylmar', 'Inman', 'ainman2e@sphinn.com', 'Male', '2020-07-17', 'Portugal');
insert into employees (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Beitris', 'Niset', 'bniset2f@irs.gov', 'Female', '2019-10-24', 'China');
insert into employees (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Britta', 'Sheryn', 'bsheryn2g@google.com.hk', 'Female', '2020-05-18', 'Russia');
insert into employees (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Alisha', 'Hullock', 'ahullock2h@kickstarter.com', 'Female', '2020-01-30', 'Poland');
insert into employees (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Talbot', 'Macvey', 'tmacvey2i@elpais.com', 'Male', '2020-06-27', 'Indonesia');
insert into employees (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Tallie', 'Ingledow', 'tingledow2j@berkeley.edu', 'Female', '2019-12-24', 'Poland');
insert into employees (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Silvester', 'Slinger', 'sslinger2k@blogspot.com', 'Male', '2019-12-09', 'Thailand');
insert into employees (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Read', 'Brayshay', 'rbrayshay2l@etsy.com', 'Male', '2020-07-28', 'Mexico');
insert into employees (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Harley', 'Venes', 'hvenes2m@google.nl', 'Male', '2020-02-19', 'Indonesia');
insert into employees (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Mable', 'Meek', 'mmeek2n@webs.com', 'Female', '2020-01-23', 'China');
insert into employees (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Diego', 'Widdicombe', 'dwiddicombe2o@uiuc.edu', 'Male', '2019-08-28', 'Philippines');
insert into employees (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Frasquito', 'Costigan', 'fcostigan2p@themeforest.net', 'Male', '2020-01-09', 'Argentina');
insert into employees (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Augustine', 'Agett', 'aagett2q@cam.ac.uk', 'Male', '2020-07-12', 'Macedonia');
insert into employees (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Leslie', 'Rustman', 'lrustman2r@blogs.com', 'Female', '2020-05-30', 'Indonesia');
